user_module:
    resource: api/user.yaml
    prefix: /user

order_module:
    resource: api/order.yaml
    prefix: /order

stock_module:
    resource: api/stock.yaml
    prefix: /stock

cart_module:
    resource: api/cart.yaml
    prefix: /cart

guest_cart_module:
    resource: api/cart.yaml
    prefix: /guest-cart
    name_prefix: guest_

image_module:
    resource: api/image.yaml
    prefix: /image

catalog_module:
    resource: api/catalog.yaml
    prefix: /catalog
