imports:
  - { resource: "@FidryAliceDataFixturesBundle/Resources/config/doctrine_orm.xml" }
  - { resource: "indexes/vue_storefront_catalog.yaml" }
  - { resource: "doctrine.yaml" }

parameters:
  sylius.model.order_item.class: 'BitBag\SyliusVueStorefrontPlugin\Sylius\Entity\Order\OrderItem'

sylius_order:
  resources:
    order_item:
      classes:
        model: BitBag\SyliusVueStorefrontPlugin\Sylius\Entity\Order\OrderItem

fidry_alice_data_fixtures:
  default_purge_mode: no_purge
  db_drivers:
    doctrine_orm: ~

framework:
  messenger:
    buses:
      bitbag_vue_storefront_plugin.command_bus:
        middleware:
          - doctrine_transaction
