imports:
  - { resource: "indexes/vue_storefront_catalog.yaml" }

framework:
  messenger:
    buses:
      bitbag_vue_storefront_plugin.command_bus:
        middleware:
          - doctrine_transaction
