imports:
    - { resource: "attribute.yaml" }
    - { resource: "category.yaml" }
    - { resource: "product.yaml" }

fos_elastica:
    clients:
        default: { host: '%env(ELASTICSEARCH_HOST)%', port: '%env(ELASTICSEARCH_PORT)%' }
