parameters:
    bitbag_vuestorefront_sylius_channel: 'US_WEB'

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }

    indexes:
        bitbag_vue_storefront_catalog:
            index_name: "vue_storefront_catalog"
            types:
                product:
                    properties:
                        enabled: ~
                        slug: { type: keyword }
                        url_key: { type: keyword }
                        url_path: { type: keyword }
                        sku: { type: keyword }
                        size: { type: integer }
                        size_options: { type: integer }
                        price: { type: float }
                        has_options: { type: boolean }
                        special_price: { type: float }
                        color: { type: integer }
                        color_options: { type: integer }
                        pattern: { type: text }
                        id: { type: long }
                        status: { type: integer }
                        weight: { type: integer }
                        visibility: { type: integer }
                        updated_at: { type: date, format: yyyy-MM-dd }
                        created_at: { type: date, format: yyyy-MM-dd }
                        special_from_date: { type: date, format: yyyy-MM-dd }
                        special_to_date: { type: date, format: yyyy-MM-dd }
                        news_from_date: { type: date, format: yyyy-MM-dd }
                        news_to_date: { type: date, format: yyyy-MM-dd }
                        description: { type: text }
                        name: { type: text }
                        configurable_children:
                            type: nested
                            properties:
                                url_key: { type: keyword }
                                has_options: { type: boolean }
                                price: { type: float }
                                sku: { type: keyword }
                                special_price: { type: float }
                        configurable_options:
                            type: nested
                            properties:
                                attribute_id: { type: long }
                                default_label: { type: text }
                                label: { type: text }
                                frontend_label: { type: text }
                                store_label: { type: text }
                                values:
                                    type: nested
                                    properties:
                                        default_label: { type: text }
                                        label: { type: text }
                                        frontend_label: { type: text }
                                        store_label: { type: text }
                                        value_index:  { type: keyword }
                        category_ids: { type: long }
                        eco_collection: { type: integer }
                        eco_collection_options: { type: integer }
                        erin_recommends: { type: integer }
                        tax_class_id: { type: long }
                    persistence:
                        driver: orm
                        model: "%sylius.model.product.class%"
                        identifier: documentId
                        model_to_elastica_transformer:
                            service: bitbag_sylius_vue_storefront_plugin.transformer.product
                        provider: ~
                        listener:
                            logger: true
                            defer: true

                category:
                    properties:
                        enabled: ~
                        updated_at: { type: date, format: yyyy-MM-dd }
                        created_at: { type: date, format: yyyy-MM-dd }
                    persistence:
                        driver: orm
                        model: "%sylius.model.taxon.class%"
                        identifier: documentId
                        model_to_elastica_transformer:
                            service: bitbag_sylius_vue_storefront_plugin.transformer.category
                        provider: ~
                        listener:
                            logger: true
                            defer: true

#                attribute:
#                    properties:
#                        enabled: ~
#                        id: { type: long }
#                        attribute_id: { type: long }
#                        options:
#                            type: nested
#                            properties:
#                                value: { type: text, index: not_analyzed }
#                    persistence:
#                        driver: orm
#                        model: "%sylius.model.product_attribute.class%"
#                        identifier: documentId
#                        model_to_elastica_transformer:
#                            service: bitbag_sylius_vue_storefront_plugin.transformer.attribute
#                        provider: ~
#                        listener:
#                            logger: true
#                            defer: true
#
#                taxrule:
#                    properties:
#                        enabled: ~
#                        id: { type: long }
#                        rates:
#                            type: nested
#                            properties:
#                                rate: { type: float }
#                    persistence:
#                        driver: orm
#                        model: "%sylius.model.tax_category.class%"
#                        identifier: documentId
#                        model_to_elastica_transformer:
#                            service: bitbag_sylius_vue_storefront_plugin.transformer.tax_rule
#                        provider: ~
#                        listener:
#                            logger: true
#                            defer: true
