parameters:
    bitbag_vuestorefront_sylius_channel: 'US_WEB'

fos_elastica:
    indexes:
        bitbag_vue_storefront_catalog:
            index_name: "vue_storefront_catalog"
            types:
                product:
                    properties:
                        enabled: ~
                    persistence:
                        driver: orm
                        model: "%sylius.model.product.class%"
                        identifier: documentId
                        model_to_elastica_transformer:
                            service: bitbag_sylius_vue_storefront_plugin.transformer.product
                        provider: ~
                        listener:
                            logger: true
                            defer: true
                category:
                    properties:
                        enabled: ~
                    persistence:
                        driver: orm
                        model: "%sylius.model.taxon.class%"
                        identifier: documentId
                        model_to_elastica_transformer:
                            service: bitbag_sylius_vue_storefront_plugin.transformer.category
                        provider: ~
                        listener:
                            logger: true
                            defer: true
#                taxrule:
#                    properties:
#                        enabled: ~
#                    persistence:
#                        driver: orm
#                        model: "%sylius.model.tax_category.class%"
#                        identifier: documentId
#                        model_to_elastica_transformer:
#                            service: bitbag_sylius_vue_storefront_plugin.transformer.tax_rule
#                        provider: ~
#                        listener:
#                            logger: true
#                            defer: true
